// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A thread that currently owns an attachment with the requested identity.
 */
export type ThreadAttachmentOwner = { threadId: string,
/**
 * Whether the owning thread is archived, not whether it is currently executing a turn.
 */
archived: boolean, };
