// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadAttachmentOwner } from "./ThreadAttachmentOwner";

/**
 * One page of matching owners, including threads without their own user messages.
 */
export type ThreadAttachmentOwnerListResponse = { data: Array<ThreadAttachmentOwner>, nextCursor: string | null, };
