// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for reverse lookup by attachment identity within this server's store.
 */
export type ThreadAttachmentOwnerListParams = { attachmentType: string, identityKey: string,
/**
 * Omitted or null returns all matches; false returns non-archived threads only.
 */
archived?: boolean | null, cursor?: string | null, limit?: number | null, };
