[package]
name = "argument_comment_lint"
version = "0.1.0"
description = "Dylint lints for Rust /*param*/ argument comments"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
bazel_native = []

[dependencies]
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "21baba9c10c5d179915cae82e6247bc2337872fb" }
dylint_linting = "6.1.0"

[dev-dependencies]
dylint_testing = "6.1.0"

[workspace]

[package.metadata.rust-analyzer]
rustc_private = true
